### PR TITLE
feat: Adobe Audition Marker Export Support

### PR DESCRIPTION
**Pull request by DanTheMan827**
# feat: Adobe Audition Marker Export Support

Adobe Audition can export markers to a file with the following format.
```
Name	Start	Duration	Time Format	Type	Description
	0:18.000	0:00.000	decimal	Cue	
	0:21.000	0:00.000	decimal	Cue	
```
Each field is separated with a tab.

# BREAKING CHANGE: No

### CODE REVIEW

**Comment by DmitryVarennikov** [comment]
Can you add [this change](https://github.com/DmitryVarennikov/cuegenerator-react/commit/b0e86a6d60ab0240588586766fe0fc9718037cc4) to your PR?

**Comment by DmitryVarennikov** [comment]
@DanTheMan827 could you test your changes in the preview channel?

**Comment by DanTheMan827** [comment]
Weirdly, it doesn't seem to work...

I'm attaching a sample marker export
[Markers.csv](https://github.com/DmitryVarennikov/cuegenerator-react/files/9162697/Markers.csv)

I've also found that Audition also supports exporting markers in a variety of different timestamp formats, including 75fps CUE 
[Markers-cue.csv](https://github.com/DmitryVarennikov/cuegenerator-react/files/9162705/Markers-cue.csv)

**Comment by DmitryVarennikov** [comment]
Did you try to test locally on your machine?

**Comment by DanTheMan827** [comment]
What I did specifically was take parseRegionsList and the requisite types and just tested against that function by giving it the entire contents of the file.

**Comment by DmitryVarennikov** [comment]
You can run the project locally using `npm run start`. Try it out and see where it fails

**Comment by DmitryVarennikov** [comment]
Closed in favor of https://github.com/DmitryVarennikov/cuegenerator-react/pull/36

**Pull request closed without merging**
